let startPlayerFrameEllipse = 5;

const images = {
    characters:{
        NinjaMan:{
            run:{
                spriteWidth:3630 / 10,
                spriteHeight:458,
                frameCount:9,
                frameEllipse: 4,
                image:null,
                source:"./Assets/Characters/NinjaMan/Images/run.png",
                collisionLeft:10,
                collisionWidth:30,
            },
            idle:{
                spriteWidth:2320 / 10,
                spriteHeight:439,
                frameCount:9,
                frameEllipse:10,
                image:null,
                source:"./Assets/Characters/NinjaMan/Images/idle.png",
                collisionLeft:5,
                collisionWidth:30
            },
            jump:{
                spriteWidth:3620 / 10,
                spriteHeight:483,
                frameCount:9,
                frameEllipse:10,
                image:null,
                source:"./Assets/Characters/NinjaMan/Images/jump.png",
                collisionLeft:10,
                collisionWidth:30
            },
            kunai:{
                width:160 * 0.2,
                height:32 * 0.2,
                positionY:1,
                power:15,
                texture:null,
                decrease:0.1,
                source:"./Assets/Characters/NinjaMan/Images/kunai.png",
            },
            throw:{
                spriteWidth:1885 / 5,
                spriteHeight:451,
                frameCount:4,
                frameEllipse:6,
                image:null,
                source:"./Assets/Characters/NinjaMan/Images/throw.png",
                collisionLeft:5,
                collisionWidth:35,
            },
            scale:0.13,
            pCount:45,
            transLeft:50,
            transTop:100,
            spriteCount:5,
            type:"NinjaMan"
        },
        NinjaGirl:{
            run:{
                spriteWidth:3760 / 10,
                spriteHeight:520,
                frameCount:9,
                frameEllipse:4,
                image:null,
                source:"./Assets/Characters/NinjaGirl/Images/run.png",
                collisionLeft:10,
                collisionWidth:30,
            },
            idle:{
                spriteWidth:2900 / 10,
                spriteHeight:500,
                frameCount:9,
                frameEllipse:5,
                image:null,
                source:"./Assets/Characters/NinjaGirl/Images/idle.png",
                collisionLeft:5,
                collisionWidth:30,
            },
            throw:{
                spriteWidth:1915 / 5,
                spriteHeight:514,
                frameCount:4,
                frameEllipse:6,
                image:null,
                source:"./Assets/Characters/NinjaGirl/Images/throw.png",
                collisionLeft:5,
                collisionWidth:35
            },
            jump:{
                spriteWidth:3990 / 10,
                spriteHeight:599,
                frameCount:9,
                frameEllipse:5,
                image:null,
                source:"./Assets/Characters/NinjaGirl/Images/jump.png",
                collisionLeft:10,
                collisionWidth:30
            },
            kunai:{
                width:160 * 0.2,
                height:32 * 0.2,
                positionY:1,
                power:15,
                decrease:0.1,
                texture:null,
                source:"./Assets/Characters/NinjaGirl/Images/kunai.png",
            },
            scale:0.13,
            spriteCount:5,
            pCount:45,
            transLeft:50,
            transTop:100,
            type:"NinjaGirl"
        },
        AdventureGirl:{
            run:{
                spriteWidth:5128 / 8,
                spriteHeight:496,
                frameCount:7,
                frameEllipse:5,
                image:null,
                source:"./Assets/Characters/AdventureGirl/Images/run.png",
                collisionLeft:45,
                collisionWidth:35,
            },
            idle:{
                spriteWidth:6410 / 10,
                spriteHeight:489,
                frameCount:9,
                frameEllipse:5,
                image:null,
                source:"./Assets/Characters/AdventureGirl/Images/idle.png",
                collisionLeft:50,
                collisionWidth:35,
            },
            jump:{
                spriteWidth:6410 / 10,
                spriteHeight:486,
                frameCount:9,
                frameEllipse:5,
                image:null,
                source:"./Assets/Characters/AdventureGirl/Images/jump.png",
                collisionLeft:40,
                collisionWidth:35
            },
            throw:{
                spriteWidth:1923 / 3,
                spriteHeight:495,
                frameCount:2,
                frameEllipse:14,
                image:null,
                source:"./Assets/Characters/AdventureGirl/Images/throw.png",
                collisionLeft:30,
                collisionWidth:35
            },
            kunai:{
                width:245 * 0.1,
                height:141 * 0.1,
                positionY:6,
                power:20,
                decrease:0.3,
                texture:null,
                source:"./Assets/Characters/AdventureGirl/Images/kunai.png",
            },
            scale:0.14,
            pCount:83,
            spriteCount:5,
            transLeft:30,
            transTop:100,
            type:"AdventureGirl"
        },
        Robot:{
            idle:{
                spriteWidth:5670 / 10,
                spriteHeight:471,
                frameCount:9,
                frameEllipse:5,
                image:null,
                source:"./Assets/Characters/Robot/Images/idle.png",
                collisionLeft:25,
                collisionWidth:30,
            }, 
            jump:{
                spriteWidth:5670 / 10,
                spriteHeight:505,
                frameCount:9,
                frameEllipse:5,
                image:null,
                source:"./Assets/Characters/Robot/Images/jump.png",
                collisionLeft:27,
                collisionWidth:30
            },
            run:{
                spriteWidth:3969 / 7,
                spriteHeight:490,
                frameCount:6,
                frameEllipse:6,
                image:null,
                source:"./Assets/Characters/Robot/Images/run.png",
                collisionLeft:27,
                collisionWidth:30
            },  
            kunai:{
                width:172 * 0.05,
                height:139 * 0.05,
                positionY:10,
                power:25,
                decrease:0.1,
                texture:null,
                source:"./Assets/Characters/Robot/Images/kunai.png",
            },
            throw:{
                spriteWidth:2268 / 4,
                spriteHeight:467,
                frameCount:3,
                frameEllipse:6,
                image:null,
                source:"./Assets/Characters/Robot/Images/throw.png",
                collisionLeft:27,
                collisionWidth:30
            },
            pCount:60,
            spriteCount:5,
            scale:0.13,
            transLeft:40,
            transTop:100,
            type:"Robot"
        },
        Dino:{
            run:{
                spriteWidth:5440 / 8,
                spriteHeight:433,
                frameCount:7,
                frameEllipse:5,
                image:null,
                source:"./Assets/Characters/Dino/Images/run.png",
                collisionLeft:95,
                collisionWidth:100,
            },
            throw:{
                spriteWidth:5440 / 8,
                spriteHeight:433,
                frameCount:7,
                frameEllipse:5,
                image:null,
                source:"./Assets/Characters/Dino/Images/run.png",
                collisionLeft:95,
                collisionWidth:100,
            },
            jump:{
                spriteWidth:4760 / 7,
                spriteHeight:431,
                frameCount:6,
                frameEllipse:5,
                image:null,
                source:"./Assets/Characters/Dino/Images/jump.png",
                collisionLeft:75,
                collisionWidth:100,
            },
            kunai:{
                width:408 * 0.15,
                height:409 * 0.15,
                positionY:5,
                power:50,
                decrease:1,
                texture:null,
                source:"./Assets/Characters/Dino/Images/kunai.png",            
            },
            scale:0.3,
            spriteCount:4,
            type:"Dino"
        },
        Police:{
            run:{
                spriteWidth:9030 / 14,
                spriteHeight:456,
                frameCount:13,
                frameEllipse: 4,
                image:null,
                source:"./Assets/Characters/Police/Images/run.png",
                collisionLeft:30,
                collisionWidth:30
            },
            idle:{
                spriteWidth:4041 / 9,
                spriteHeight:452,
                frameCount:8,
                frameEllipse:10,
                image:null,
                source:"./Assets/Characters/Police/Images/idle.png",
                collisionLeft:5,
                collisionWidth:30
            },
            jump:{
                spriteWidth:2732 / 5,
                spriteHeight:445,
                frameCount:4,
                frameEllipse:10,
                image:null,
                source:"./Assets/Characters/Police/Images/jump.png",
                collisionLeft:10,
                collisionWidth:30
            },
            kunai:{
                width:245 * 0.1,
                height:141 * 0.1,
                positionY:12,
                power:20,
                decrease:0.3,
                texture:null,
                source:"./Assets/Characters/Police/Images/kunai.png",
            },
            throw:{
                spriteWidth:3016 / 4,
                spriteHeight:454,
                frameCount:3,
                frameEllipse:6,
                image:null,
                source:"./Assets/Characters/Police/Images/throw.png",
                collisionLeft:30,
                collisionWidth:30,
            },
            scale:0.13,
            pCount:60,
            transLeft:40,
            spriteCount:5,
            transTop:100,
            type:"Police"
        },
        Sheriff:{
            run:{
                spriteWidth:7136 / 8,
                spriteHeight:523,
                frameCount:7,
                frameEllipse: 5,
                image:null,
                source:"./Assets/Characters/Sheriff/Images/run.png",
                collisionLeft:50,
                collisionWidth:25
            },
            kunai:{
                width:246 * 0.2,
                height:142 * 0.2,
                positionY:12,
                power:30,
                texture:null,
                decrease:0.5,
                source:"./Assets/Characters/Sheriff/Images/kunai.png",
            },
            idle:{
                spriteWidth:8920 / 10,
                spriteHeight:532,
                frameCount:9,
                frameEllipse: 4,
                image:null,
                source:"./Assets/Characters/Sheriff/Images/idle.png",
                collisionLeft:40,
                collisionWidth:30
            },
            jump:{
                spriteWidth:8028 / 9,
                spriteHeight:588,
                frameCount:8,
                frameEllipse: 14,
                image:null,
                source:"./Assets/Characters/Sheriff/Images/jump.png",
                collisionLeft:45,
                collisionWidth:25
            },
            throw:{
                spriteWidth:7136 / 8,
                spriteHeight:523,
                frameCount:7,
                frameEllipse: 4,
                image:null,
                source:"./Assets/Characters/Sheriff/Images/throw.png",
                collisionLeft:50,
                collisionWidth:25
            },
            pCount:80,
            spriteCount:5,
            scale:0.13,
            transLeft:20,
            transTop:100,
            type:"Sheriff"
        },
        OldSheriff:{
            run:{
                spriteWidth:7136 / 8,
                spriteHeight:524,
                frameCount:7,
                frameEllipse: 5,
                source:"./Assets/Characters/OldSheriff/Images/run.png",
                image:null,
                collisionLeft:50,
                collisionWidth:25,
            },
            kunai:{
                width:233 * 0.2,
                height:134 * 0.2,
                positionY:5,
                power:35,
                decrease:0.5,
                texture:null,
                source:"./Assets/Characters/OldSheriff/Images/kunai.png",
            },
            idle:{
                spriteWidth:8920 / 10,
                spriteHeight:536,
                frameCount:9,
                frameEllipse: 4,
                source:"./Assets/Characters/OldSheriff/Images/idle.png",
                image:null,
                collisionLeft:40,
                collisionWidth:30
            },
            jump:{
                spriteWidth:8028 / 9,
                spriteHeight:577,
                frameCount:8,
                frameEllipse: 12,
                source:"./Assets/Characters/OldSheriff/Images/jump.png",
                image:null,
                collisionLeft:45,
                collisionWidth:25
            },
            throw:{
                spriteWidth:7136 / 8,
                spriteHeight:523,
                frameCount:7,
                frameEllipse: 4,
                source:"./Assets/Characters/OldSheriff/Images/throw.png",
                image:null,
                collisionLeft:50,
                collisionWidth:25
            },
            pCount:80,
            spriteCount:5,
            scale:0.13,
            transLeft:20,
            transTop:100,
            type:"OldSheriff"
        }
    },
    enemies:{
        ZombieMan:{
            run:{
                spriteWidth:3870 / 9,
                spriteHeight:519,
                frameCount:8,
                frameEllipse:11,
                image:null,
                source:"./Assets/Enemies/ZombieMan/Images/run.png",
                positionX:15,
                collisionWidth:20,
                collisionHeight:33
            },
            attack:{
                spriteWidth:3440 / 8,
                spriteHeight:519,
                frameCount:7,
                frameEllipse:5,
                source:"./Assets/Enemies/ZombieMan/Images/attack.png",
                positionX:15,
                collisionWidth:20,
                image:null,
                type2:"attack",
                collisionHeight:33
            },
            scale:0.13,
        },
        ZombieGirl:{
            run:{
                spriteWidth:5209 / 10,
                spriteHeight:575,
                frameCount:9,
                frameEllipse:11,
                image:null,
                positionX:15,
                collisionWidth:26,
                collisionHeight:35,
                source:"./Assets/Enemies/ZombieGirl/Images/run.png"
            },
            attack:{
                spriteWidth:4168 / 8,
                spriteHeight:576,
                frameCount:7,
                frameEllipse:5,
                image:null,
                positionX:15,
                collisionWidth:26,
                collisionHeight:35,
                source:"./Assets/Enemies/ZombieGirl/Images/attack.png",
                type2:"attack"

            },
            scale:0.13

        },
        GrassMonster:{
            run:{
                spriteWidth:5676 / 6,
                spriteHeight:821,
                frameCount:5,
                frameEllipse:5,
                image:null,
                collisionWidth:50,
                positionX:15,
                collisionHeight:35,
                source:"./Assets/Enemies/GrassMonster/Images/run.png"
            },
            scale:0.08

        },
        Skeleton2:{
            run:{
                spriteWidth:8505 / 7,
                spriteHeight:616,
                frameCount:6,
                frameEllipse:5,
                image:null,
                collisionWidth:50,
                positionX:45,
                collisionHeight:35,
                source:"./Assets/Enemies/GrassMonster/Images/run2.png"
            },
            attack:{
                spriteWidth:3645 / 3,
                spriteHeight:751,
                frameCount:2,
                frameEllipse:5,
                collisionWidth:50,
                positionX:45,
                image:null,
                collisionHeight:40,
                source:"./Assets/Enemies/GrassMonster/Images/attack.png"
            },
            scale:0.12
        },
        Spider:{
            run:{
                spriteWidth:4704 / 7,
                spriteHeight:552,
                frameCount:6,
                frameEllipse:7,
                collisionWidth:30,
                positionX:15,
                image:null,
                collisionHeight:35,
                source:"./Assets/Enemies/Spider/Images/run.png"
            },
            attack:{
                spriteWidth:4180 / 5,
                spriteHeight:528,
                frameCount:4,
                image:null,
                collisionWidth:30,
                positionX:23,
                collisionHeight:35,
                frameEllipse:7,
                source:"./Assets/Enemies/Spider/Images/attack.png"
            },
            scale:0.1
        },
        birdsp:{
            run:{
                spriteWidth:1000 / 11,
                spriteHeight:90,
                frameCount:10,
                frameEllipse:3,
                image:null,
                collisionWidth:30,
                positionX:13,
                source:"./Assets/Enemies/birdsp.png",
                type2:"Skeleton"
            }
        },
        Bee:{
            run:{
                spriteWidth:1100 / 13,
                spriteHeight:87,
                frameCount:12,
                frameEllipse:5,
                image:null,
                collisionWidth:30,
                positionX:13,
                source:"./Assets/Enemies/bee.png",
                type2:"Bee"
            }
        },
        Skeleton:{
            run:{
                spriteWidth:750 / 7,
                spriteHeight:87,
                frameCount:6,
                frameEllipse:7,
                image:null,
                collisionWidth:30,
                positionX:13,
                source:"./Assets/Enemies/skeleton.png",
                type2:"Skeleton"
            },
        },
        Bomb:{
            run:{
                spriteWidth:500 / 4,
                spriteHeight:125,
                frameCount:3,
                frameEllipse: 12,
                image:null,
                scale:0.3,
                collisionWidth:30,
                collisionHeight:10,
                positionX:5,
                source:"./Assets/Enemies/Bomb.png",
            },
            scale:0.4
        },
        spriteCount:13
    },
    icons:{
        diamond:{
            spriteWidth:128,
            spriteHeight:128,
            source:"./Assets/Icons/diamond.png",
            texture:null
        },
        sheild:{
            spriteWidth:512,
            spriteHeight:512,
            source:"./Assets/Icons/sheild.png",
            texture:null
        },
        timer:{
            spriteWidth:512,
            spriteHeight:512,
            source:"./Assets/Icons/timer.png",
            texture:null
        },
        goldCoin:{
            spriteWidth:894 / 6,
            spriteHeight:149,
            source:"./Assets/Icons/goldCoin.png",
            texture:null
        },
        heart:{
            spriteWidth:512,
            spriteHeight:512,
            source:"./Assets/Icons/heart.png",
            texture:null
        },
        xPoint:{
            spriteWidth:128,
            spriteHeight:128,
            source:"./Assets/Icons/xPoint.png",
            texture:null
        },
        dino:{
            spriteWidth:512,
            spriteHeight:512,
            source:"./Assets/Icons/dino.png",
            texture:null
        },
        bubble:{
            spriteWidth:512,
            spriteHeight:512,
            source:"./Assets/Icons/bubble.png",
            texture:null
        },
        iconSoundOff:{
            source:"./Assets/Icons/iconSoundOff.png",
        },
        iconSoundOn:{
            source:"./Assets/Icons/iconSoundOn.png",
        },
        iconPause:{
            source:"./Assets/Icons/iconPause.png",
        },
        iconCancel:{
            source:"./Assets/Icons/iconCancel.png",
        },
    },
    platforms:{
        Winter:{
            Objects:{           
                one:{
                    spriteWidth:97,
                    spriteHeight:78,
                    source:"./Assets/Platforms/Winter/Object/Crystal.png"
                },
                two:{
                    spriteWidth:511,
                    spriteHeight:201,
                    source:"./Assets/Platforms/Winter/Object/Igloo.png",
                    type:"igloo"
                },
                three:{
                    spriteWidth:193,
                    spriteHeight:210,
                    source:"./Assets/Platforms/Winter/Object/SnowMan.png",
                    type:"snowMan"
                },
                four:{
                    spriteWidth:124,
                    spriteHeight:78,
                    source:"./Assets/Platforms/Winter/Object/Stone.png"
                },
                five:{
                    spriteWidth:364,
                    spriteHeight:280,
                    source:"./Assets/Platforms/Winter/Object/Tree1.png",
                    type:"tree"
                },
                six:{
                    spriteWidth:228,
                    spriteHeight:280,
                    source:"./Assets/Platforms/Winter/Object/Tree2.png"
                }
            },
            Tiles:{
                first:{
                    spriteWidth:128,
                    spriteHeight:128,
                    source:"./Assets/Platforms/Winter/Tile/1.png",
                    type:"static"
                },
                two:{
                    spriteWidth:128,
                    spriteHeight:128,
                    source:"./Assets/Platforms/Winter/Tile/2.png",
                    type:"static"
                },
                three:{
                    spriteWidth:128,
                    spriteHeight:128,
                    source:"./Assets/Platforms/Winter/Tile/3.png",
                    type:"static"
                },
                four:{
                    spriteWidth:128,
                    spriteHeight:128,
                    source:"./Assets/Platforms/Winter/Tile/4.png",
                    type:"static"
                },
                five:{
                    spriteWidth:128,
                    spriteHeight:128,
                    source:"./Assets/Platforms/Winter/Tile/5.png",
                    type:"static"
                },
                six:{
                    spriteWidth:128,
                    spriteHeight:128,
                    source:"./Assets/Platforms/Winter/Tile/6.png",
                    type:"static"
                },
                fourTeen:{
                    spriteWidth:128,
                    spriteHeight:93,
                    source:"./Assets/Platforms/Winter/Tile/14.png",
                    type:"static"
                },
                fiftTeen:{
                    spriteWidth:128,
                    spriteHeight:93,
                    source:"./Assets/Platforms/Winter/Tile/15.png",
                    type:"static"
                },
                sixTeen:{
                    spriteWidth:128,
                    spriteHeight:93,
                    source:"./Assets/Platforms/Winter/Tile/16.png",
                    type:"static"
                }
            },
            bg:{
                spriteWidth:1280,
                spriteHeight:960,
                source:"./Assets/Platforms/Winter/BG.png"
            },
            sign1:{
                spriteWidth:87,
                spriteHeight:94,
                source:"./Assets/Platforms/Winter/Object/Sign1.png",
            },
            crate:{
                spriteWidth:101,
                spriteHeight:101,
                source:"./Assets/Platforms/Winter/Crate.png"
            },
            obstacle:{
                spriteWidth:128,
                spriteHeight:99,
                source:"./Assets/Platforms/Winter/obstacle.png",
                texture:null
            },
            spriteCount:19,
            type:"Winter"
        },
        Desert:{
            Objects:{
                one:{
                    spriteWidth:313,
                    spriteHeight:260,
                    source:"./Assets/Platforms/Desert/Object/Tree.png",
                    texture:null
                },
                two:{
                    spriteWidth:131,
                    spriteHeight:74,
                    source:"./Assets/Platforms/Desert/Object/Bush2.png",
                    texture:null
                },
                three:{
                    spriteWidth:108,
                    spriteHeight:111,
                    source:"./Assets/Platforms/Desert/Object/Cactus1.png",
                    texture:null
                },
                four:{
                    spriteWidth:70,
                    spriteHeight:45,
                    source:"./Assets/Platforms/Desert/Object/Cactus2.png",
                    texture:null
                },
                five:{
                    spriteWidth:86,
                    spriteHeight:96,
                    source:"./Assets/Platforms/Desert/Object/Cactus3.png",
                    texture:null
                },
                six:{
                    spriteWidth:102,
                    height:50,
                    source:"./Assets/Platforms/Desert/Object/Grass1.png",
                    texture:null
                },
                seven:{
                    spriteWidth:102,
                    spriteHeight:50,
                    source:"./Assets/Platforms/Desert/Object/Grass2.png",
                    texture:null
                },
                eight:{
                    spriteWidth:150,
                    spriteHeight:51,
                    source:"./Assets/Platforms/Desert/Object/Skeleton.png",
                    texture:null
                },
                nine:{
                    spriteWidth:124,
                    spriteHeight:73,
                    source:"./Assets/Platforms/Desert/Object/Stone.png",
                    texture:null
                },
                ten:{
                    spriteWidth:145,
                    spriteHeight:88,
                    source:"./Assets/Platforms/Desert/Object/Bush1.png",
                    texture:null
                }
            },
            Tiles:{
                first:{
                    spriteWidth:128,
                    spriteHeight:128,
                    source:"./Assets/Platforms/Desert/Tile/1.png",
                    texture:null
                },
                two:{
                    spriteWidth:128,
                    spriteHeight:128,
                    source:"./Assets/Platforms/Desert/Tile/2.png",
                    texture:null
                },
                three:{
                    spriteWidth:128,
                    spriteHeight:128,
                    source:"./Assets/Platforms/Desert/Tile/3.png",
                    texture:null
                },
                four:{
                    spriteWidth:128,
                    spriteHeight:128,
                    source:"./Assets/Platforms/Desert/Tile/4.png",
                    texture:null
                },
                five:{
                    spriteWidth:128,
                    spriteHeight:128,
                    source:"./Assets/Platforms/Desert/Tile/5.png",
                    texture:null
                },
                six:{
                    spriteWidth:128,
                    spriteHeight:128,
                    source:"./Assets/Platforms/Desert/Tile/6.png",
                    texture:null
                },
                fourTeen:{
                    spriteWidth:128,
                    spriteHeight:128,
                    source:"./Assets/Platforms/Desert/Tile/14.png",
                    texture:null
                },
                fiftTeen:{
                    spriteWidth:128,
                    spriteHeight:128,
                    source:"./Assets/Platforms/Desert/Tile/15.png",
                    texture:null
                },
                sixTeen:{
                    spriteWidth:128,
                    spriteHeight:128,
                    source:"./Assets/Platforms/Desert/Tile/16.png",
                    texture:null
                }
            },
            bg:{
                spriteWidth:1280,
                spriteHeight:960,
                source:"./Assets/Platforms/Desert/BG.png",
                texture:null
            },
            sign1:{
                spriteWidth:85,
                spriteHeight:88,
                source:"./Assets/Platforms/Desert/Object/Sign1.png",
                texture:null
            },
            obstacle:{
                spriteWidth:128,
                spriteHeight:99,
                source:"./Assets/Platforms/Desert/obstacle.png",
                texture:null
            },
            crate:{
                    spriteWidth:101,
                    spriteHeight:101,
                    source:"./Assets/Platforms/Desert/Crate.png",
                    texture:null
            },
            spriteCount:23
        },
        Night:{
            Objects:{
                one:{
                    spriteWidth:286,
                    spriteHeight:239,
                    source:"./Assets/Platforms/Night/Object/Tree.png"
                },
                two:{
                    spriteWidth:182,
                    spriteHeight:90,
                    source:"./Assets/Platforms/Night/Object/Bush1.png"
                }, 
                three:{
                    spriteWidth:100,
                    spriteHeight:64,
                    source:"./Assets/Platforms/Night/Object/Bush2.png"
                }, 
                four:{
                    spriteWidth:132,
                    spriteHeight:74,
                    source:"./Assets/Platforms/Night/Object/DeadBush.png"
                }, 
                five:{
                    spriteWidth:102,
                    spriteHeight:50,
                    source:"./Assets/Platforms/Night/Object/Skeleton.png"
                },
                six:{
                    spriteWidth:54,
                    spriteHeight:55,
                    source:"./Assets/Platforms/Night/Object/TombStone2.png"
                }, 
                seven:{
                    spriteWidth:53,
                    spriteHeight:76,
                    source:"./Assets/Platforms/Night/Object/TombStone1.png"
                },
            },
            Tiles:{
                first:{
                    spriteWidth:128,
                    spriteHeight:128,
                    source:"./Assets/Platforms/Night/Tile/1.png",
                    type:"static"
                },
                two:{
                    spriteWidth:128,
                    spriteHeight:128,
                    source:"./Assets/Platforms/Night/Tile/2.png",
                    type:"static"
                },
                three:{
                    spriteWidth:128,
                    spriteHeight:128,
                    source:"./Assets/Platforms/Night/Tile/3.png",
                    type:"static"
                },
                four:{
                    spriteWidth:128,
                    spriteHeight:128,
                    source:"./Assets/Platforms/Night/Tile/4.png",
                    type:"static"
                },
                five:{
                    spriteWidth:128,
                    spriteHeight:128,
                    source:"./Assets/Platforms/Night/Tile/5.png",
                    type:"static"
                },
                six:{
                    spriteWidth:128,
                    spriteHeight:128,
                    source:"./Assets/Platforms/Night/Tile/6.png",
                    type:"static"
                },
                fourTeen:{
                    spriteWidth:128,
                    spriteHeight:128,
                    source:"./Assets/Platforms/Night/Tile/14.png",
                    type:"static"
                },
                fiftTeen:{
                    spriteWidth:128,
                    spriteHeight:128,
                    source:"./Assets/Platforms/Night/Tile/15.png",
                    type:"static"
                },
                sixTeen:{
                    spriteWidth:128,
                    spriteHeight:128,
                    source:"./Assets/Platforms/Night/Tile/16.png",
                    type:"static"
                }
            },
            bg:{
                spriteWidth:1000,
                spriteHeight:750,
                source:"./Assets/Platforms/Night/BG.png"
            },
            sign1:{
                spriteWidth:91,
                spriteHeight:93,
                source:"./Assets/Platforms/Night/Object/Sign1.png"
            },
            crate:{
                spriteWidth:106,
                spriteHeight:106,
                source:"./Assets/Platforms/Night/Crate.png"
            },
            obstacle:{
                spriteWidth:128,
                spriteHeight:99,
                source:"./Assets/Platforms/Night/obstacle.png",
                texture:null
            },
            spriteCount:20
        },
        Summer:{
            Objects:{
                one:{
                    spriteWidth:282,
                    spriteHeight:301,
                    source:"./Assets/Platforms/Summer/Object/Tree2.png"
                },
                two:{
                    spriteWidth:282,
                    spriteHeight:275,
                    source:"./Assets/Platforms/Summer/Object/Tree3.png"
                },  
                three:{
                    spriteWidth:116,
                    spriteHeight:44,
                    source:"./Assets/Platforms/Summer/Object/Tree1.png"
                },
                four:{
                    spriteWidth:133,
                    spriteHeight:65,
                    source:"./Assets/Platforms/Summer/Object/Bush1.png"
                }, 
                five:{
                    spriteWidth:133,
                    spriteHeight:65,
                    source:"./Assets/Platforms/Summer/Object/Bush2.png"
                }, 
                six:{
                    spriteWidth:73,
                    spriteHeight:47,
                    source:"./Assets/Platforms/Summer/Object/Bush3.png"
                },
                seven:{
                    spriteWidth:90,
                    spriteHeight:54,
                    source:"./Assets/Platforms/Summer/Object/Stone.png"
                },
                eight:{
                    spriteWidth:49,
                    spriteHeight:41,
                    source:"./Assets/Platforms/Summer/Object/Mushroom1.png"
                },
                nine:{
                    spriteWidth:50,
                    spriteHeight:41,
                    source:"./Assets/Platforms/Summer/Object/Mushroom2.png"
                },
                ten:{
                    spriteWidth:73,
                    spriteHeight:46,
                    source:"./Assets/Platforms/Summer/Object/Bush4.png"
                },
            },
            Tiles:{
                first:{
                    spriteWidth:128,
                    spriteHeight:128,
                    source:"./Assets/Platforms/Summer/Tile/1.png",
                    type:"static"
                },
                two:{
                    spriteWidth:128,
                    spriteHeight:128,
                    source:"./Assets/Platforms/Summer/Tile/2.png",
                    type:"static"
                },
                three:{
                    spriteWidth:128,
                    spriteHeight:128,
                    source:"./Assets/Platforms/Summer/Tile/3.png",
                    type:"static"
                },
                four:{
                    spriteWidth:128,
                    spriteHeight:128,
                    source:"./Assets/Platforms/Summer/Tile/4.png",
                    type:"static"
                },
                five:{
                    spriteWidth:128,
                    spriteHeight:128,
                    source:"./Assets/Platforms/Summer/Tile/5.png",
                    type:"static"
                },
                six:{
                    spriteWidth:128,
                    spriteHeight:128,
                    source:"./Assets/Platforms/Summer/Tile/6.png",
                    type:"static"
                },
                fourTeen:{
                    spriteWidth:128,
                    spriteHeight:93,
                    source:"./Assets/Platforms/Summer/Tile/14.png",
                    type:"static"
                },
                fiftTeen:{
                    spriteWidth:128,
                    spriteHeight:93,
                    source:"./Assets/Platforms/Summer/Tile/15.png",
                    type:"static"
                },
                sixTeen:{
                    spriteWidth:128,
                    spriteHeight:93,
                    source:"./Assets/Platforms/Summer/Tile/16.png",
                    type:"static"
                }
            },
            bg:{
                spriteWidth:1000,
                spriteHeight:750,
                source:"./Assets/Platforms/Summer/BG.png"
            },
            sign1:{
                spriteWidth:85,
                spriteHeight:88,
                source:"./Assets/Platforms/Summer/Object/Sign1.png",
            },
            crate:{
                spriteWidth:101,
                spriteHeight:101,
                source:"./Assets/Platforms/Summer/Crate.png"
            },
            obstacle:{
                spriteWidth:128,
                spriteHeight:99,
                source:"./Assets/Platforms/Night/obstacle.png",
                texture:null
            },
            spriteCount:23
        },
    },
    jumpEffects:{
        effect2:{
            spriteWidth:3927 / 7,
            spriteHeight:249,
            frameCount:7,
            frameEllipse:8,
            image:null,
            source:"./Assets/JumpEffects/jumpEffect2.png",
            type:"absolute"
        },
    },
    effects:{
        bombEffect:{
            spriteWidth:1200 / 5,
            spriteHeight:304,
            frameCount:4,
            frameEllipse:12,
            image:null,
            source:"./Assets/Icons/bombEffect.png",
            type:"absolute"
        },
        transformEffect:{
            spriteWidth:2000 / 6,
            spriteHeight:549,
            frameCount:5,
            frameEllipse:10,
            image:null,
            source:"./Assets/Icons/transform.png",
            type:"absolute"
        },
    },
    goldCoin:{
        frames: {
            frame0: {
                frame: {
                    x: 9,
                    y: 9,
                    w: 149,
                    h: 149
                }
            },
            frame1: {
                frame: {
                    x: 176,
                    y: 9,
                    w: 149,
                    h: 149
                }
            },
            frame2: {
                frame: {
                    x: 343,
                    y: 9,
                    w: 149,
                    h: 149
                }
            },
            frame3: {
                frame: {
                    x: 510,
                    y: 9,
                    w: 149,
                    h: 149
                }
            },
            frame4: {
                frame: {
                    x: 677,
                    y: 9,
                    w: 149,
                    h: 149
                }
            },
            frame5: {
                frame: {
                    x: 844,
                    y: 9,
                    w: 149,
                    h: 149
                }
            }
        },
        meta: {
            image: "./Assets/Coins/sprite.png",
            texture:null,
            format: "RGBA8888",
            scale: 4
        },
        animations:{
            walk:["frame0","frame1","frame2","frame3","frame4","frame5"]
        }
    }
}