const sounds = {
    characters:{
        NinjaMan:{
            start:{
                source:"../Assets/Characters/NinjaMan/Sounds/start.mp3"
            },
            throw:{
                    source:"./Assets/Characters/NinjaMan/Sounds/throw2.mp3",
            },
            dead:{
                source:"./Assets/Characters/NinjaMan/Sounds/dead.mp3",
            }
        },
        NinjaGirl:{
            start:{
                source:"./Assets/Characters/NinjaGirl/Sounds/start.mp3",
            },  
            throw:{
                    source:"./Assets/Characters/NinjaMan/Sounds/throw2.mp3",
            },
            dead:{
                source:"./Assets/Characters/NinjaGirl/Sounds/dead.mp3",
            }
        },
        AdventureGirl:{
            throw:{
                source:"./Assets/Characters/AdventureGirl/Sounds/throw.mp3",
            },
            dead:{
                source:"./Assets/Characters/NinjaGirl/Sounds/dead.mp3",
            },
            start:{
                source:"./Assets/Characters/AdventureGirl/Sounds/start.mp3",
            },
        },
        AdventureMan:{
            start:{
                source:"./Assets/Characters/AdventureMan/Sounds/start.mp3",
            },
            throw:{
                source:"./Assets/Characters/AdventureGirl/Sounds/throw.mp3",
            },
            dead:{
                source:"./Assets/Characters/NinjaMan/Sounds/dead.mp3",
            }
        },
        Dino:{
            start:{
                source:"./Assets/Characters/Dino/Sounds/start.mp3"
            },
            throw:{
                source:"./Assets/Characters/Dino/Sounds/throw.mp3",
            },
            dead:{
                source:"./Assets/Characters/Dino/Sounds/dead.mp3",
            }
        },
        Robot:{
            start:{
                source:"./Assets/Characters/Robot/Sounds/start.ogg"
            },
            dead:{
                source:"./Assets/Characters/Robot/Sounds/dead.mp3"
            },
            throw:{
                source:"./Assets/Characters/Robot/Sounds/throw.mp3"
            }
        },
        Santa:{
            start:{
                source:"./Assets/Characters/Santa/Sounds/start.mp3"
            },
            throw:{
                source:"./Assets/Characters/Santa/Sounds/throw.mp3"
            },
            dead:{
                source:"./Assets/Characters/Santa/Sounds/dead.mp3"
            }
        },
        JackFree:{
            dead:{
                source:"./Assets/Characters/NinjaMan/Sounds/dead.mp3",
            },
            start:{
                source:"./Assets/Characters/JackFree/Sounds/start.mp3",
            }
        },
        Police:{
            start:{
                source:"../Assets/Characters/Police/Sounds/start.mp3"
            },
            throw:{
                    source:"./Assets/Characters/Police/Sounds/throw.mp3",
            },
            dead:{
                source:"./Assets/Characters/NinjaMan/Sounds/dead.mp3",
            }
        },
        Sheriff:{
            start:{
                source:"../Assets/Characters/Sheriff/Sounds/start.mp3"
            },
            throw:{
                    source:"./Assets/Characters/Sheriff/Sounds/throw.mp3",
            },
            dead:{
                source:"./Assets/Characters/Sheriff/Sounds/dead.mp3",
            }
        },
        OldSheriff:{
            start:{
                source:"../Assets/Characters/OldSheriff/Sounds/start.mp3"
            },
            throw:{
                    source:"./Assets/Characters/OldSheriff/Sounds/throw.mp3",
            },
            dead:{
                source:"./Assets/Characters/Sheriff/Sounds/dead.mp3",
            }
        }
    },
    Enemies:{
        ZombieMan:{
            attack:{
                source:"./Assets/Enemies/ZombieMan/Sounds/attack.mp3"
            },
            start:{
                source:"./Assets/Enemies/ZombieMan/Sounds/start.mp3",
            }
        },
        ZombieGirl:{
            attack:{
                source:"./Assets/Enemies/ZombieGirl/Sounds/attack.mp3"
            },
            start:{
                source:"./Assets/Enemies/ZombieMan/Sounds/start.mp3",
            }
        },
        GrassMonster:{
            attack:{
                source:"./Assets/Enemies/GrassMonster/Sounds/attack.mp3"
            }
        },
        Skeleton2:{
            attack:{
                source:"./Assets/Enemies/GrassMonster/Sounds/attack2.mp3"
            }
        },
        Spider:{
            attack:{
                source:"./Assets/Enemies/Spider/Sounds/attack.mp3"
            }
        },
        Bomb:{
            attack:{
                source:"./Assets/IconsSounds/bombAttack.mp3"
            },
            explosion:{
                source:"./Assets/IconsSounds/explosion.mp3"
            }
        }
    },
    UpEnemies:{
        Bee:{
            start:{
                source:"./Assets/IconsSounds/beeStart.mp3",
                sound:null
            }
        },
        Skeleton:{
            start:{
                source:"./Assets/IconsSounds/skeletonStart.mp3",
                sound:null
            }
        },
        SpinyBird:{
            start:{
                source:"./Assets/IconsSounds/spinyBirdStart.mp3",
                sound:null

            }
        }
    },
    coins:{
        sound4:{
            source:"./Assets/Coins/sound4.wav"
        },
        sound5:{
            source:"./Assets/Coins/sound5.mp3"
        },
    },
    power:{
        kam:{
            source:"./Assets/IconsSounds/kam.mp3",
        },
        powerDown:{
            source:"./Assets/IconsSounds/powerDown.mp3",
        },
        heart:{
            source:"./Assets/IconsSounds/heart.mp3",
        },
        success:{
            source:"./Assets/IconsSounds/success.mp3"
        }
    },
    icons:{
        crate:{
            source:"./Assets/IconsSounds/crate.mp3",
            sound:null,
            isDom:false
        },
        jump:{
            source:"./Assets/Characters/Sounds/jump.mp3",
            sound:null,
            isDom:false
        },
        bloodSound:{
            source:"./Assets/IconsSounds/bloodSound.mp3",
            sound:null,
            isDom:false,
        },
        click:{
            source:"./Assets/IconsSounds/click.mp3",
            sound:null,
            isDom:true
        },
        homeSound:{
            source:"./Assets/IconsSounds/homeSound.mp3",
            sound:null,
            volume:0,
            isDom:true,
            loop:true
        },
        gameSound:{
            source:"./Assets/IconsSounds/gameSound.mp3",
            volume:0,
            loop:true,
            isDom:true,
            sound:null
        },
        isBuy:{
            source:"./Assets/IconsSounds/isBuy.mp3",
            sound:null,
            isDom:true
        },
        select:{
            source:"./Assets/IconsSounds/select.mp3",
            sound:null,
            isDom:true
        },
        gameActive:{
            source:"./Assets/IconsSounds/gameActive.mp3",
            sound:null,
            isDom:true
        }
    }
}